# Generated by Django 5.2.4 on 2025-07-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility_type', models.CharField(choices=[('classroom', 'কক্ষ সংখ্যা'), ('computer', 'কম্পিউটার ব্যবহার'), ('seats', 'ছাত্রছাত্রীর আসন সংখ্যা'), ('multimedia', 'মাল্টিমিডিয়া ক্লাসরুম'), ('transport', 'যানবাহন সুবিধা')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='FontAwesome icon class', max_length=50)),
                ('count', models.IntegerField(default=0, help_text='Number/Count for this facility')),
                ('unit', models.CharField(blank=True, help_text="Unit (e.g., 'টি', 'জন', 'খানা')", max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='facilities/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Facility Information',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InformationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Information Service',
            },
        ),
        migrations.CreateModel(
            name='InformationSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='information_slider/')),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Information Sliders',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
