# Generated by Django 5.2.4 on 2025-07-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_facultyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='শিরোনাম')),
                ('address', models.TextField(verbose_name='ঠিকানা')),
                ('phone', models.CharField(max_length=30, verbose_name='ফোন নম্বর')),
                ('email', models.EmailField(max_length=254, verbose_name='ইমেইল')),
                ('map_embed', models.TextField(blank=True, help_text='গুগল ম্যাপ এম্বেড কোড (ঐচ্ছিক)', verbose_name='গুগল ম্যাপ এম্বেড কোড')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
            ],
            options={
                'verbose_name': 'যোগাযোগের তথ্য',
                'verbose_name_plural': 'যোগাযোগের তথ্যসমূহ',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='নাম')),
                ('phone', models.CharField(max_length=30, verbose_name='ফোন নম্বর')),
                ('title', models.CharField(max_length=200, verbose_name='বার্তার শিরোনাম')),
                ('message', models.TextField(verbose_name='বার্তার বিবরণ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='পাঠানোর সময়')),
                ('is_read', models.BooleanField(default=False, verbose_name='পড়া হয়েছে')),
            ],
            options={
                'verbose_name': 'যোগাযোগ বার্তা',
                'verbose_name_plural': 'যোগাযোগ বার্তাসমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
