# Generated by Django 5.2.4 on 2025-07-26 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_contactinfo_contactmessage'),
    ]

    operations = [
    ]
