# Generated by Django 5.2.4 on 2025-07-26 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_importantlink_principalrole_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='principalmessage',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Principal/Head Message', 'verbose_name_plural': 'Principal/Head Messages'},
        ),
        migrations.AlterModelOptions(
            name='principalrole',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Principal/Head Role', 'verbose_name_plural': 'Principal/Head Roles'},
        ),
        migrations.AlterField(
            model_name='principalmessage',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.principalrole', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='principalrole',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='principalrole',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Role Name'),
        ),
    ]
