# Generated by Django 5.2.4 on 2025-07-26 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_news_newslink'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='শিরোনাম')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='উপশিরোনাম')),
                ('banner', models.ImageField(blank=True, upload_to='about/banner/', verbose_name='ব্যানার')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
            ],
            options={
                'verbose_name': 'About পেজ কনটেন্ট',
                'verbose_name_plural': 'About পেজ কনটেন্টসমূহ',
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_type', models.CharField(choices=[('history', 'ইতিহাস'), ('brief_info', 'সংক্ষিপ্ত পরিচিতি'), ('approval', 'অনুমোদন'), ('recognition', 'স্বীকৃতি'), ('aims', 'লক্ষ্য ও উদ্দেশ্য'), ('custom', 'Custom')], default='custom', max_length=30, verbose_name='সেকশন টাইপ')),
                ('title', models.CharField(max_length=200, verbose_name='শিরোনাম')),
                ('content', models.TextField(verbose_name='বিস্তারিত')),
                ('image', models.ImageField(blank=True, upload_to='about/sections/', verbose_name='ছবি')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রম')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='web.aboutpagecontent')),
            ],
            options={
                'verbose_name': 'About সেকশন',
                'verbose_name_plural': 'About সেকশনসমূহ',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
