# Generated by Django 5.2.4 on 2025-07-26 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_aboutpagecontent_aboutsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='লিঙ্কের শিরোনাম')),
                ('url', models.URLField(verbose_name='লিঙ্ক')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রম')),
            ],
            options={
                'verbose_name': 'গুরুত্বপূর্ণ লিঙ্ক',
                'verbose_name_plural': 'গুরুত্বপূর্ণ লিঙ্কসমূহ',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutNewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='সংবাদের শিরোনাম')),
                ('date', models.CharField(max_length=50, verbose_name='তারিখ')),
                ('link', models.URLField(verbose_name='লিঙ্ক')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রম')),
            ],
            options={
                'verbose_name': 'সংবাদ আইটেম',
                'verbose_name_plural': 'সংবাদ আইটেমসমূহ',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='আমাদের সম্পর্কে (About Us)', max_length=200, verbose_name='পৃষ্ঠার শিরোনাম')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
            ],
            options={
                'verbose_name': 'আমাদের সম্পর্কে পৃষ্ঠা',
                'verbose_name_plural': 'আমাদের সম্পর্কে পৃষ্ঠা',
            },
        ),
        migrations.CreateModel(
            name='AboutPrincipalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='অধ্যক্ষের বাণী', max_length=200, verbose_name='শিরোনাম')),
                ('name', models.CharField(max_length=100, verbose_name='নাম')),
                ('message', models.TextField(verbose_name='বার্তা')),
                ('photo', models.ImageField(blank=True, upload_to='about/principal/', verbose_name='ছবি')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রম')),
            ],
            options={
                'verbose_name': 'অধ্যক্ষের বাণী (আমাদের সম্পর্কে)',
                'verbose_name_plural': 'অধ্যক্ষের বাণী (আমাদের সম্পর্কে)',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolAims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='লক্ষ্য ও উদ্দেশ্য', max_length=200, verbose_name='শিরোনাম')),
                ('content', models.TextField(verbose_name='বিস্তারিত বিবরণ')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রম')),
            ],
            options={
                'verbose_name': 'লক্ষ্য ও উদ্দেশ্য',
                'verbose_name_plural': 'লক্ষ্য ও উদ্দেশ্য',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='অনুমোদন', max_length=200, verbose_name='শিরোনাম')),
                ('content', models.TextField(verbose_name='বিস্তারিত বিবরণ')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রম')),
            ],
            options={
                'verbose_name': 'অনুমোদন',
                'verbose_name_plural': 'অনুমোদন',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='শাখার নাম')),
                ('location', models.CharField(max_length=200, verbose_name='ঠিকানা')),
                ('established_year', models.CharField(max_length=20, verbose_name='প্রতিষ্ঠাকাল')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রম')),
            ],
            options={
                'verbose_name': 'শাখা',
                'verbose_name_plural': 'শাখাসমূহ',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolBriefInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='সংক্ষিপ্ত তথ্য', max_length=200, verbose_name='শিরোনাম')),
                ('description', models.TextField(verbose_name='বিস্তারিত বিবরণ')),
                ('teachers_count', models.CharField(default='৫০+', max_length=20, verbose_name='শিক্ষক-শিক্ষিকার সংখ্যা')),
                ('departments_count', models.CharField(default='৫', max_length=20, verbose_name='বিভাগের সংখ্যা')),
                ('classrooms_count', models.CharField(default='৩০+', max_length=20, verbose_name='ক্লাসরুমের সংখ্যা')),
                ('students_count', models.CharField(default='১০০০+', max_length=20, verbose_name='শিক্ষার্থীর সংখ্যা')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রম')),
            ],
            options={
                'verbose_name': 'সংক্ষিপ্ত তথ্য',
                'verbose_name_plural': 'সংক্ষিপ্ত তথ্য',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='প্রতিষ্ঠানের ইতিহাস', max_length=200, verbose_name='শিরোনাম')),
                ('content', models.TextField(verbose_name='বিস্তারিত বিবরণ')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রম')),
            ],
            options={
                'verbose_name': 'প্রতিষ্ঠানের ইতিহাস',
                'verbose_name_plural': 'প্রতিষ্ঠানের ইতিহাস',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='স্বীকৃতি', max_length=200, verbose_name='শিরোনাম')),
                ('content', models.TextField(verbose_name='বিস্তারিত বিবরণ')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রম')),
            ],
            options={
                'verbose_name': 'স্বীকৃতি',
                'verbose_name_plural': 'স্বীকৃতি',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='about_page',
        ),
        migrations.CreateModel(
            name='AimPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point', models.CharField(max_length=500, verbose_name='লক্ষ্য পয়েন্ট')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রম')),
                ('aim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='web.schoolaims', verbose_name='লক্ষ্য')),
            ],
            options={
                'verbose_name': 'লক্ষ্য পয়েন্ট',
                'verbose_name_plural': 'লক্ষ্য পয়েন্টসমূহ',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AboutPageContent',
        ),
        migrations.DeleteModel(
            name='AboutSection',
        ),
    ]
