# Generated by Django 5.2.4 on 2025-07-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_aboutlink_aboutnewsitem_aboutpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolrecognition',
            name='document',
            field=models.FileField(blank=True, help_text='PDF, DOC, or image file', null=True, upload_to='recognition_documents/', verbose_name='স্বীকৃতি দলিল'),
        ),
        migrations.AddField(
            model_name='schoolrecognition',
            name='document_title',
            field=models.CharField(blank=True, help_text='Document title to display', max_length=200, verbose_name='দলিলের শিরোনাম'),
        ),
    ]
