# Generated by Django 5.2.4 on 2025-07-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_schoolrecognition_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='category',
            field=models.CharField(choices=[('special_officer', 'Special Officer'), ('teacher', 'Teacher'), ('management_board', 'Management Board')], default='teacher', max_length=32, verbose_name='Category'),
        ),
    ]
