# Generated by Django 5.2.4 on 2025-07-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_teacher_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Upload a .ico or .png file for the browser tab icon.', null=True, upload_to='school/'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='YouTube URL'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='logo',
            field=models.ImageField(help_text='Upload the main logo for the navbar.', upload_to='school/'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='name',
            field=models.CharField(max_length=255, verbose_name='School Name'),
        ),
    ]
