# Generated by Django 5.2.4 on 2025-07-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_schoolinfo_facebook_url_schoolinfo_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='principalmessage',
            name='show_on_home_page',
            field=models.BooleanField(default=False, help_text='Check this box to feature this message on the home page. Only one can be selected.', verbose_name='Show on home page'),
        ),
    ]
