# Generated by Django 5.2.4 on 2025-07-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_principalmessage_show_on_home_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sliders/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Sliders',
                'ordering': ['-created_at'],
            },
        ),
    ]
