# Generated by Django 5.2.4 on 2025-08-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='reg_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Registration Number'),
        ),
    ]
