# Generated by Django 5.2.4 on 2025-08-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_schoolinfo_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('school', 'School'), ('student', 'Student'), ('teacher', 'Teacher')], max_length=20),
        ),
    ]
