# Generated by Django 5.2.4 on 2025-08-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_alter_gallery_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAndNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='শিরোনাম')),
                ('primary_image', models.ImageField(upload_to='event_news_primary/', verbose_name='প্রধান ছবি')),
                ('description', models.TextField(verbose_name='বিবরণ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির সময়')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='আপডেটের সময়')),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=20, verbose_name='অবস্থা')),
                ('type', models.CharField(choices=[('event', 'Event'), ('news', 'News')], max_length=20, verbose_name='ধরন')),
            ],
            options={
                'verbose_name': 'ইভেন্ট ও সংবাদ',
                'verbose_name_plural': 'ইভেন্ট ও সংবাদসমূহ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventNewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_news_gallery/')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='ছবির শিরোনাম')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ইভেন্ট ও সংবাদ ছবি',
                'verbose_name_plural': 'ইভেন্ট ও সংবাদ ছবিসমূহ',
            },
        ),
        migrations.DeleteModel(
            name='AboutNewsItem',
        ),
        migrations.AddField(
            model_name='eventandnews',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, to='web.eventnewsimage', verbose_name='গ্যালারি ছবিসমূহ'),
        ),
    ]
