# Generated by Django 5.2.4 on 2025-08-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_eventandnews_eventnewsimage_delete_aboutnewsitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventandnews',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='eventandnews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventandnews',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='eventandnews',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, to='web.gallery'),
        ),
        migrations.AlterField(
            model_name='eventandnews',
            name='primary_image',
            field=models.ImageField(upload_to='event_news_primary/'),
        ),
        migrations.AlterField(
            model_name='eventandnews',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='eventandnews',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='eventandnews',
            name='type',
            field=models.CharField(choices=[('EVENT', 'Event'), ('NEWS', 'News')], max_length=20),
        ),
    ]
