# Generated by Django 5.2.4 on 2025-08-02 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_remove_eventandnews_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventandnews',
            name='gallery_images',
        ),
        migrations.CreateModel(
            name='EventAndNewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_news_gallery/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='web.eventandnews')),
            ],
            options={
                'verbose_name': 'ইভেন্ট ও সংবাদের ছবি',
                'verbose_name_plural': 'ইভেন্ট ও সংবাদের ছবিসমূহ',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
