# Generated by Django 5.2.4 on 2025-08-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_remove_eventandnews_gallery_images_eventandnewsimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='অধ্যক্ষের বাণী', max_length=200, verbose_name='শিরোনাম')),
                ('name', models.CharField(max_length=100, verbose_name='নাম')),
                ('position', models.CharField(max_length=100, verbose_name='পদবী/পদ')),
                ('message', models.TextField(verbose_name='বার্তা')),
                ('photo', models.ImageField(blank=True, upload_to='about/principal/', verbose_name='ছবি')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('serial_no', models.IntegerField(default=0, verbose_name='ক্রমিক নম্বর')),
            ],
            options={
                'verbose_name': 'বার্তা (আমাদের সম্পর্কে)',
                'verbose_name_plural': 'বার্তাসমূহ (আমাদের সম্পর্কে)',
                'ordering': ['serial_no', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AboutPrincipalMessage',
        ),
    ]
