# Generated by Django 5.2.4 on 2025-08-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_aboutmessage_delete_aboutprincipalmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmessage',
            name='show_on_home_page',
            field=models.BooleanField(default=False, help_text='হোম পেজে দেখানোর জন্য টিক দিন। শুধুমাত্র serial_no=1 এর জন্য সক্রিয় করুন।', verbose_name='হোম পেজে দেখান'),
        ),
    ]
