# Generated by Django 5.2.4 on 2025-08-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_aboutmessage_show_on_home_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='category',
            field=models.CharField(choices=[('special_officer', 'Special Officer'), ('teacher', 'Teacher'), ('management_board', 'Management Board'), ('administration', 'Administration'), ('kormochari', 'Kormochari Brindo')], default='teacher', max_length=32, verbose_name='Category'),
        ),
    ]
