# Generated by Django 5.2.1 on 2025-08-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_teacher_department_alter_teacher_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('teacher', 'Teacher'), ('management', 'Management'), ('administration', 'Administration'), ('staff', 'Staff (Kormochari)')], default='teacher', max_length=32, verbose_name='Category')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('position', models.CharField(max_length=200, verbose_name='Position')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Department')),
                ('education', models.CharField(blank=True, max_length=200, verbose_name='Education')),
                ('experience', models.CharField(blank=True, help_text='Years of experience', max_length=100, verbose_name='Experience')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('photo', models.ImageField(blank=True, upload_to='faculty_photos/', verbose_name='Photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Faculty Member',
                'verbose_name_plural': 'Faculty Members',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.TextField(blank=True),
        ),
    ]
