# Generated by Django 5.2.1 on 2025-08-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_facultymember_remove_teacher_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolrecognition',
            name='document',
        ),
        migrations.RemoveField(
            model_name='schoolrecognition',
            name='document_title',
        ),
        migrations.AddField(
            model_name='schoolapproval',
            name='image',
            field=models.ImageField(blank=True, help_text='A4 ratio image of approval document', null=True, upload_to='approval_documents/', verbose_name='অনুমোদন দলিল (ছবি)'),
        ),
        migrations.AddField(
            model_name='schoolrecognition',
            name='image',
            field=models.ImageField(blank=True, help_text='A4 ratio image of recognition document', null=True, upload_to='recognition_documents/', verbose_name='স্বীকৃতি দলিল (ছবি)'),
        ),
    ]
