# Generated by Django 5.2.1 on 2025-08-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_remove_schoolrecognition_document_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolBranch',
        ),
    ]
