# Generated by Django 5.2.1 on 2025-08-04 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_delete_schoolbranch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='পাঠ্যক্রমের শিরোনাম')),
                ('file', models.FileField(upload_to='syllabus/', verbose_name='পাঠ্যক্রম ফাইল')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.class', verbose_name='শ্রেণি')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.department', verbose_name='বিভাগ')),
            ],
            options={
                'verbose_name': 'পাঠ্যক্রম',
                'verbose_name_plural': 'পাঠ্যক্রমসমূহ',
                'ordering': ['-updated_at'],
            },
        ),
    ]
