# Generated by Django 5.2.1 on 2025-08-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='file',
            field=models.FileField(blank=True, upload_to='syllabus/', verbose_name='পাঠ্যক্রম ফাইল'),
        ),
    ]
