# Generated by Django 5.2.1 on 2025-08-05 03:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_alter_syllabus_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='ভর্তির শিরোনাম')),
                ('file', models.FileField(upload_to='admissions/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='ভর্তির ফাইল')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.class', verbose_name='শ্রেণি')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.department', verbose_name='বিভাগ')),
            ],
            options={
                'verbose_name': 'ভর্তি',
                'verbose_name_plural': 'ভর্তিসমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
