# Generated by Django 5.2.1 on 2025-08-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Full YouTube URL (e.g., https://www.youtube.com/watch?v=dQw4w9WgXcQ)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='The YouTube video ID (e.g., dQw4w9WgXcQ) - will be auto-extracted from URL', max_length=50),
        ),
    ]
