# Generated by Django 5.2.1 on 2025-08-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_alter_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='numeric_value',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('roll_number', 'class_name')},
        ),
    ]
