# Generated by Django 5.2.1 on 2025-08-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_alter_class_numeric_value_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
    ]
