# Generated by Django 5.2.1 on 2025-08-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_alter_student_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolhistory',
            options={'verbose_name': 'প্রতিষ্ঠানের ইতিহাস', 'verbose_name_plural': 'প্রতিষ্ঠানের ইতিহাস'},
        ),
        migrations.RemoveField(
            model_name='schoolhistory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='schoolhistory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='schoolhistory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='schoolhistory',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='schoolhistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='history/'),
        ),
        migrations.AlterField(
            model_name='schoolhistory',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='schoolhistory',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
